# Generated by Django 4.1.7 on 2023-03-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selslist',
            name='accumulated_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selslist',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selslist',
            name='is_admin',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
