# Generated by Django 4.1.7 on 2023-03-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0002_selslist_accumulated_time_selslist_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Calendar',
            },
        ),
    ]
