# Generated by Django 4.1.7 on 2023-03-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0003_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='enterNames',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='calendar',
            name='eventId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='selslist',
            name='latencyCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selslist',
            name='school_id',
            field=models.CharField(default='', max_length=500),
        ),
    ]
