# Generated by Django 4.1.7 on 2023-04-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0004_calendar_enternames_calendar_eventid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
