# Generated by Django 4.1.7 on 2023-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0005_alter_calendar_enddate_alter_calendar_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_NameList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(default='', max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('state_point', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=500)),
                ('attendanceTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Calendar_NameList',
            },
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='enterNames',
        ),
        migrations.AddField(
            model_name='calendar',
            name='enterNames',
            field=models.ManyToManyField(to='selsapp.calendar_namelist'),
        ),
    ]
