# Generated by Django 4.1.7 on 2023-05-05 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0006_calendar_namelist_remove_calendar_enternames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_namelist',
            name='attendanceTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
