# Generated by Django 4.1.7 on 2023-05-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0007_alter_calendar_namelist_attendancetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar_namelist',
            options={'managed': True},
        ),
    ]
