# Generated by Django 4.1.7 on 2023-05-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0008_alter_calendar_namelist_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_namelist',
            name='state_point',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
