# Generated by Django 4.1.7 on 2023-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0010_alter_calendar_namelist_state_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_namelist',
            name='state_point',
            field=models.IntegerField(default=0),
        ),
    ]
