# Generated by Django 4.2.1 on 2023-06-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0011_alter_calendar_namelist_state_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='selslist',
            name='accumulated_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selslist',
            name='department',
            field=models.CharField(default='', max_length=500),
        ),
    ]
