# Generated by Django 4.2.1 on 2023-07-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0015_alter_calendar_namelist_attendancetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='enterNames',
        ),
        migrations.AddField(
            model_name='calendar',
            name='name_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='selsapp.calendar_namelist'),
        ),
    ]
