# Generated by Django 4.2.1 on 2023-07-01 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0017_calendar_namelist_calendar_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='name_list',
        ),
    ]
