# Generated by Django 4.2.1 on 2023-08-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0019_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='reference',
            table='Reference',
        ),
    ]
