# Generated by Django 4.2.1 on 2023-08-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0022_alter_calendar_enddate_alter_calendar_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='activity_time',
            field=models.IntegerField(default=0),
        ),
    ]
