# Generated by Django 4.2.1 on 2023-08-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0023_calendar_activity_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('minus_time', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Rule',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='selslist',
            name='penalty_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
