# Generated by Django 4.2.1 on 2023-08-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0024_rule_selslist_penalty_cnt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
    ]
