# Generated by Django 4.2.1 on 2023-08-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0025_delete_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_TB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.IntegerField()),
                ('file_location', models.FileField(blank=True, upload_to='Uploaded Files/%y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='reference',
            name='file_location',
        ),
    ]
