# Generated by Django 4.2.1 on 2023-08-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0026_file_tb_remove_reference_file_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file_tb',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='file_tb',
            table='File_TB',
        ),
    ]
