# Generated by Django 4.2.1 on 2023-08-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0027_alter_file_tb_options_alter_file_tb_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='content',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
