# Generated by Django 4.2.1 on 2023-08-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0029_alter_reference_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_namelist',
            name='calendar_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='namelists', to='selsapp.calendar'),
        ),
    ]
