# Generated by Django 4.2.1 on 2023-08-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0031_rename_calendar_id_calendar_namelist_calendar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar_namelist',
            name='calendar',
        ),
        migrations.AddField(
            model_name='calendar_namelist',
            name='calendar_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
