# Generated by Django 4.2.1 on 2023-08-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0032_remove_calendar_namelist_calendar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'managed': True},
        ),
    ]
