# Generated by Django 4.2.1 on 2023-08-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0035_alter_calendar_namelist_late_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar_namelist',
            name='late_time',
            field=models.CharField(default='', max_length=500),
        ),
    ]
