# Generated by Django 4.2.1 on 2023-08-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0036_alter_calendar_namelist_late_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selslist',
            name='penalty_cnt',
        ),
        migrations.AddField(
            model_name='calendar_namelist',
            name='latency_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendar_namelist',
            name='penalty_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendar_namelist',
            name='service_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='selslist',
            name='penalty_point_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
