# Generated by Django 4.2.1 on 2023-08-25 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0037_remove_selslist_penalty_cnt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar_namelist',
            old_name='penalty_point',
            new_name='penalty_cnt',
        ),
    ]
