# Generated by Django 4.2.1 on 2023-08-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selsapp', '0039_rename_penalty_cnt_calendar_namelist_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar_namelist',
            name='calculated',
            field=models.IntegerField(default=0),
        ),
    ]
